###
GET  http://localhost:8000/users HTTP/1.1
###
GET  http://localhost:8000/users/101 HTTP/1.1

###
POST http://localhost:8000/users HTTP/1.1
content-type: application/x-www-form-urlencoded
id=123&username=eby&age=25
###

PUT http://localhost:8000/users/123 HTTP/1.1
//content-type: application/x-www-form-urlencoded
//id=123&username=eby&age=25




###
DELETE http://localhost:8000/users/123